export const ALL_BUSSCHEDULE_REQUEST = "ALL_BUSSCHEDULE_REQUEST";
export const ALL_BUSSCHEDULE_SUCESS = "ALL_BUSSCHEDULE_SUCESS";
export const ALL_BUSSCHEDULE_FAIL = "ALL_BUSSCHEDULE_FAIL";
export const CLEAR_ERR = "CLEAR_ERR";
