export const ALL_TRAINSCHEDULE_REQUEST = "ALL_TRAINSCHEDULE_REQUEST";
export const ALL_TRAINSCHEDULE_SUCCESS = "ALL_TRAINSCHEDULE_SUCCESS";
export const ALL_TRAINSCHEDULE_FAIL = "ALL_TRAINSCHEDULE_FAIL";
export const CLEAR_ERR = "CLEAR_ERR";
