export const ALL_FLIGHTSCHEDULE_REQUEST = "ALL_FLIGHTSCHEDULE_REQUEST";
export const ALL_FLIGHTSCHEDULE_SUCESS = "ALL_FLIGHTSCHEDULE_SUCESS";
export const ALL_FLIGHTSCHEDULE_FAIL = "ALL_FLIGHTSCHEDULE_FAIL";
export const CLEAR_ERR = "CLEAR_ERR";
