export const ALL_FLIGHTSCHEDULE_REQUEST = "ALL_FLIGHTSCHEDULE_REQUEST";
export const ALL_FLIGHTSCHEDULE_SUCESS = "ALL_FLIGHTSCHEDULE_SUCESS";
export const ALL_FLIGHTSCHEDULE_FAIL = "ALL_FLIGHTSCHEDULE_FAIL";
export const CLEAR_ERR = "CLEAR_ERR";

export const GET_FLIGHTSCHEDULE_REQUEST = "GET_FLIGHTSCHEDULE_REQUEST";
export const GET_FLIGHTSCHEDULE_SUCCESS = "GET_FLIGHTSCHEDULE_SUCCESS";
export const GET_FLIGHTSCHEDULE_FAIL = "GET_FLIGHTSCHEDULE_FAIL";