export const SET_LOGGEDIN_USER = "SET_USER";
export const SET_LOGGEDOUT_USER = "SET_LOGGEDOUT_USER";

export const REFRESH_STATE = "REFRESH_STATE";
export const REFRESH_STATE_REQUEST = "REFRESH_STATE_REQUEST";
export const SET_FORGET_PASSWORD_USER_EMAIL = "SET_FORGET_PASSWORD_USER_EMAIL";
export const RESET_FORGET_PASSWORD_USER_EMAIL =
  "RESET_FORGET_PASSWORD_USER_EMAIL";

export const SET_USER_SEARCH = "SET_USER_SEARCH";
export const SET_IS_SIGNING = "SET_IS_SIGNING";
export const RESET_IS_SIGNING = "RESET_IS_SIGNING";

export const GET_PASSENGER_DETAILS_REQUEST = "GET_PASSENGER_DETAILS_REQUEST";
export const GET_PASSENGER_DETAILS_SUCCESS = "GET_PASSENGER_DETAILS_SUCCESS";
export const GET_PASSENGER_DETAILS_FAIL = "GET_PASSENGER_DETAILS_FAIL";

export const USER_BOOKING_RECORD_REQUEST = "USER_BOOKING_RECORD_REQUEST";
export const USER_BOOKING_RECORD_SUCCESS = "USER_BOOKING_RECORD_SUCCESS";
export const USER_BOOKING_RECORD_FAIL = "USER_BOOKING_RECORD_FAIL";
